name: Unity Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  unity-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode: [editmode]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          unityVersion: 2022.3.0f1
          testMode: ${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testResults: TestResults_${{ matrix.testMode }}.xml
          failOnFailedTests: true
          githubAnnotations: true